spring.redis:
  enable: true
  host: redis-14684.c292.ap-southeast-1-1.ec2.cloud.redislabs.com
  port: 14684
  username: default
  password: fTtEE6lSVyditgZMHDP4Lz4nOGtuTeMt
  timeout: 4000 # 连接或读取超时时长（毫秒）
  database: 0
  redisson:
    file: classpath:redisson.yml
  jedis:
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 2 # 连接池中的最小空闲连接