server:
  port: 8106

spring:
  # ShardingSphere 配置项
  shardingsphere:
    datasource:
      # 所有数据源的名字
      names: gm1, gm2
      # gm1 数据源配置 00
      gm1:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/gm1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: gongmin
        password: gongmin
      # gm2 数据源配置
      gm2:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/gm2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: gongmin
        password: gongmin
    # 分片规则
    sharding:
      tables:
        # user 表配置
        user:
          actualDataNodes: gm1.user_$->{[0,2,4]}, gm2.user_$->{[1,3,5]} # 映射到 gm1 和 gm2 数据源的 user 表们
          key-generator: # 主键生成策略
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              algorithm-expression: gm$->{id % 2 + 1}
              sharding-column: id
          table-strategy:
            inline:
              algorithm-expression: user_$->{id % 6}
              sharding-column: id
        # user_role 表配置
        user_role:
          actualDataNodes: gm2.user_role # 仅映射到 gm2 数据源的 user_role 表
    # 拓展属性配置
    props:
      sql:
        show: true # 打印 SQL

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: org.example.sharding.jdbc.entity # 配置数据库实体包路径