server:
  port: 8100

spring:
  application:
    name: eureka
  security:
    user:
      name: gongmin
      password: gongmin

# eureka配置
eureka:
  server:
    enable-self-preservation: true  # 关闭自我保护
  instance:
    hostname: eureka1 # 别名
  client:
    fetch-registry: false # 不自己调用自己
    register-with-eureka: false # 不向自己注册


