server:
  port: 8103

logging:
  level:
    root: info # 默认日志级别

# 数据源配置
spring:
  datasource:
    username: yield
    password: yield
    url: jdbc:mysql://47.110.90.30:3306/yielddb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.example.mybatis.entity