server:
  port: 8103

logging:
  level:
    root: info # 默认日志级别

# 数据源配置
spring:
  datasource:
    username: [db_username]
    password: [db_password]
    url: jdbc:mysql://[db_ip]:[db_port]/[db_name]]?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.example.mybatis.entity