server:
  port: 8102

spring:
  application:
    name: demo-feign-client
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    metadataMap:
      nodeId: ${client.nodeId}
  client:
    service-url:
      defaultZone: http://gongmin:gongmin@localhost:8100/eureka

demo:
  mybatis:
    serverUrl: http://localhost:8103

# 海康威视摄像头accessToken请求参数
hkws:
  url: https://open.ys7.com
  appKey: f78d4eeb5cff491eb65914dc9ec94968
  secret: ec12908fb7f058e095f185ec190d372a