server:
  port: 8103

logging:
  level:
    root: info # 默认日志级别
    org.example.mybatis.mapper: debug

# 数据源配置
spring:
  datasource:
    username: gongmin
    password: gongmin
    url: jdbc:mysql://localhost:3306/gm1?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.example.mybatis.entity
  configuration:
    cache-enabled: true